CREATE TABLE organization (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100),
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE user (
  username VARCHAR(64) NOT NULL,
  password VARCHAR(64) NOT NULL,
  org_id INT,
  PRIMARY KEY (username),
  CONSTRAINT
    FOREIGN KEY (org_id) REFERENCES organization (id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE team (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(64),
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE userteam (
  id INT NOT NULL AUTO_INCREMENT,
  user VARCHAR(64) NOT NULL,
  team INT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT
    FOREIGN KEY (user) REFERENCES user (username)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT
    FOREIGN KEY (team) REFERENCES team (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;
